### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by hayesall** [kkroy36/RFGB#6]
Haven't seen major updates since last December. If I'm correct, it would likely be easier to split my fork into a separate project going forward.

**Comment by kkroy36** [comment]
Ya It is still in development. I am not sure when I'm going to work on it again. The current version is theoretically correct (Minus the regression, I'm going to modify that in a bit after the final version of the AAMAS paper is submitted). So, fork the latest one and go ahead and split it into a different project and play with it.

**Comment by hayesall** [comment]
Sure thing, I'll remove the pull request and develop elsewhere.
